name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --manifest-path Rust_B-tree/B_Plus_Tree --verbose
    - name: Run tests
      run: cargo test --manifest-path Rust_B-tree/B_Plus_Tree/ --verbose
